/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    speakers: Speaker;
    leaders: Leader;
    'sermon-series': SermonSery;
    sermons: Sermon;
    fellowships: Fellowship;
    activities: Activity;
    'ministry-categories': MinistryCategory;
    pages: Page;
    'payload-kv': PayloadKv;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    speakers: SpeakersSelect<false> | SpeakersSelect<true>;
    leaders: LeadersSelect<false> | LeadersSelect<true>;
    'sermon-series': SermonSeriesSelect<false> | SermonSeriesSelect<true>;
    sermons: SermonsSelect<false> | SermonsSelect<true>;
    fellowships: FellowshipsSelect<false> | FellowshipsSelect<true>;
    activities: ActivitiesSelect<false> | ActivitiesSelect<true>;
    'ministry-categories': MinistryCategoriesSelect<false> | MinistryCategoriesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'zh') | ('en' | 'zh')[];
  globals: {
    'site-settings': SiteSetting;
    'page-home': PageHome;
    'page-about': PageAbout;
    'page-announcements': PageAnnouncement;
    'page-give': PageGive;
    'page-gainesville-dew': PageGainesvilleDew;
    'page-fellowships': PageFellowship;
    'page-leadership': PageLeadership;
    'page-contact': PageContact;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'page-home': PageHomeSelect<false> | PageHomeSelect<true>;
    'page-about': PageAboutSelect<false> | PageAboutSelect<true>;
    'page-announcements': PageAnnouncementsSelect<false> | PageAnnouncementsSelect<true>;
    'page-give': PageGiveSelect<false> | PageGiveSelect<true>;
    'page-gainesville-dew': PageGainesvilleDewSelect<false> | PageGainesvilleDewSelect<true>;
    'page-fellowships': PageFellowshipsSelect<false> | PageFellowshipsSelect<true>;
    'page-leadership': PageLeadershipSelect<false> | PageLeadershipSelect<true>;
    'page-contact': PageContactSelect<false> | PageContactSelect<true>;
  };
  locale: 'en' | 'zh';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alt text for accessibility (bilingual)
   */
  alt?: string | null;
  caption?: string | null;
  prefix?: string | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speakers".
 */
export interface Speaker {
  id: number;
  name: string;
  title?: string | null;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  photo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leaders".
 */
export interface Leader {
  id: number;
  name: string;
  title: string;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  photo?: (number | null) | Media;
  email?: string | null;
  /**
   * Lower numbers appear first in the leadership list.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sermon-series".
 */
export interface SermonSery {
  id: number;
  name: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  coverImage?: (number | null) | Media;
  startDate?: string | null;
  /**
   * Uncheck to archive this series without deleting it.
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sermons".
 */
export interface Sermon {
  id: number;
  title: string;
  speaker: number | Speaker;
  /**
   * Include both English and Chinese references, e.g. "John 15:1-8 (約翰福音 15:1-8)"
   */
  scripture: string;
  date: string;
  series?: (number | null) | SermonSery;
  /**
   * Chinese sermon YouTube embed URL, e.g. https://www.youtube.com/embed/XXXXX
   */
  youtubeLink?: string | null;
  /**
   * English sermon YouTube embed URL (when a separate English recording exists)
   */
  englishYoutubeLink?: string | null;
  /**
   * Direct link to MP3 or podcast episode
   */
  audioLink?: string | null;
  /**
   * Optional sermon notes or outline (bilingual)
   */
  notes?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Custom thumbnail; falls back to YouTube thumbnail if omitted
   */
  thumbnail?: (number | null) | Media;
  /**
   * Pin this sermon to the top of the archive
   */
  isFeatured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fellowships".
 */
export interface Fellowship {
  id: number;
  name: string;
  /**
   * URL-safe identifier, e.g. "campus", "friday-bible-study". Auto-fill from name.
   */
  slug: string;
  schedule: string;
  location: string;
  contact: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  image?: (number | null) | Media;
  /**
   * Show this fellowship as the hero/banner card at the top of the grid.
   */
  isFeatured?: boolean | null;
  /**
   * Lower numbers appear first. Use to manually sort the fellowship grid.
   */
  order?: number | null;
  /**
   * Uncheck to hide this fellowship without deleting it.
   */
  isActive?: boolean | null;
  /**
   * Life-stage category this fellowship belongs to (used for filtering).
   */
  ministryCategory?: ('kids' | 'youth' | 'college' | 'adults' | 'senior-adults' | 'discipleship') | null;
  /**
   * Optional Instagram profile URL, e.g. https://www.instagram.com/gccc_alpha/
   */
  instagramUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities".
 */
export interface Activity {
  id: number;
  title: string;
  /**
   * Name of the fellowship group hosting this activity (free text, bilingual).
   */
  fellowship: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  date: string;
  /**
   * Display time string, e.g. "6:30 PM"
   */
  time?: string | null;
  location?: string | null;
  /**
   * Activity photos — first photo is used as the hero image.
   */
  photos?:
    | {
        photo: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ministry-categories".
 */
export interface MinistryCategory {
  id: number;
  /**
   * Stable ID used by Fellowship.ministryCategory to reference this category.
   */
  categoryId: 'kids' | 'youth' | 'college' | 'adults' | 'senior-adults' | 'discipleship';
  label: string;
  ageRange?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Full-width banner image for the ministry category page.
   */
  bannerImage?: (number | null) | Media;
  /**
   * Hex accent color used for UI highlights, e.g. "#4A90D9"
   */
  color?: string | null;
  /**
   * Display sort order — lower numbers appear first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * URL key for this page. Use: home | about | fellowships | sermons | calendar | contact | give | announcements | prayer | gainesville-dew | leadership
   */
  slug: string;
  title?: string | null;
  blocks?:
    | (
        | {
            backgroundImage?: (number | null) | Media;
            eyebrow?: string | null;
            heading: string;
            subheading?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            image?: (number | null) | Media;
            eyebrow?: string | null;
            heading: string;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            scheduleItems?:
              | {
                  time: string;
                  label: string;
                  sub?: string | null;
                  id?: string | null;
                }[]
              | null;
            watchLiveUrl?: string | null;
            watchLiveLabel?: string | null;
            findUsLabel?: string | null;
            addressLine?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'sundayService';
          }
        | {
            image?: (number | null) | Media;
            eyebrow?: string | null;
            heading: string;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            ctaLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'prayerFeature';
          }
        | {
            heading: string;
            items?:
              | {
                  fellowship?: string | null;
                  title: string;
                  dateLabel?: string | null;
                  description?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  photos?:
                    | {
                        photo: number | Media;
                        id?: string | null;
                      }[]
                    | null;
                  /**
                   * Only used while migrating images to the media library.
                   */
                  legacyPhotoPaths?:
                    | {
                        path?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'activities';
          }
        | {
            churchPortrait?: (number | null) | Media;
            proclamationOfFaith?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            historyHeading?: string | null;
            historyBody?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            documents?:
              | {
                  label: string;
                  year?: string | null;
                  description?: string | null;
                  file?: (number | null) | Media;
                  legacyPdfPath?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'churchHistory';
          }
        | {
            heading?: string | null;
            body?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            items?:
              | {
                  date: string;
                  title: string;
                  body?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'announcementsList';
          }
        | {
            eyebrow?: string | null;
            heading?: string | null;
            subheading?: string | null;
            issues?:
              | {
                  title: string;
                  date: string;
                  description?: string | null;
                  file?: (number | null) | Media;
                  legacyPdfPath?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsletter';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            methods?:
              | {
                  icon?: string | null;
                  title: string;
                  description?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  detail?: string | null;
                  id?: string | null;
                }[]
              | null;
            taxNote?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            scripture?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'give';
          }
        | {
            modalTitle: string;
            modalSubtitle?: string | null;
            introText?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            faqs?:
              | {
                  question: string;
                  answer?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  id?: string | null;
                }[]
              | null;
            closingNote?: string | null;
            closeButtonLabel?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'visitorFaq';
          }
        | {
            worshipTimesLine?: string | null;
            instagramUrl?: string | null;
            whoWeAreLinks?:
              | {
                  label: string;
                  page?: string | null;
                  id?: string | null;
                }[]
              | null;
            getConnectedLinks?:
              | {
                  label: string;
                  page?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'footer';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'speakers';
        value: number | Speaker;
      } | null)
    | ({
        relationTo: 'leaders';
        value: number | Leader;
      } | null)
    | ({
        relationTo: 'sermon-series';
        value: number | SermonSery;
      } | null)
    | ({
        relationTo: 'sermons';
        value: number | Sermon;
      } | null)
    | ({
        relationTo: 'fellowships';
        value: number | Fellowship;
      } | null)
    | ({
        relationTo: 'activities';
        value: number | Activity;
      } | null)
    | ({
        relationTo: 'ministry-categories';
        value: number | MinistryCategory;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  prefix?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speakers_select".
 */
export interface SpeakersSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  bio?: T;
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leaders_select".
 */
export interface LeadersSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  bio?: T;
  photo?: T;
  email?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sermon-series_select".
 */
export interface SermonSeriesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  coverImage?: T;
  startDate?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sermons_select".
 */
export interface SermonsSelect<T extends boolean = true> {
  title?: T;
  speaker?: T;
  scripture?: T;
  date?: T;
  series?: T;
  youtubeLink?: T;
  englishYoutubeLink?: T;
  audioLink?: T;
  notes?: T;
  thumbnail?: T;
  isFeatured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "fellowships_select".
 */
export interface FellowshipsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  schedule?: T;
  location?: T;
  contact?: T;
  description?: T;
  image?: T;
  isFeatured?: T;
  order?: T;
  isActive?: T;
  ministryCategory?: T;
  instagramUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_select".
 */
export interface ActivitiesSelect<T extends boolean = true> {
  title?: T;
  fellowship?: T;
  description?: T;
  date?: T;
  time?: T;
  location?: T;
  photos?:
    | T
    | {
        photo?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ministry-categories_select".
 */
export interface MinistryCategoriesSelect<T extends boolean = true> {
  categoryId?: T;
  label?: T;
  ageRange?: T;
  description?: T;
  bannerImage?: T;
  color?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              backgroundImage?: T;
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              id?: T;
              blockName?: T;
            };
        sundayService?:
          | T
          | {
              image?: T;
              eyebrow?: T;
              heading?: T;
              body?: T;
              scheduleItems?:
                | T
                | {
                    time?: T;
                    label?: T;
                    sub?: T;
                    id?: T;
                  };
              watchLiveUrl?: T;
              watchLiveLabel?: T;
              findUsLabel?: T;
              addressLine?: T;
              id?: T;
              blockName?: T;
            };
        prayerFeature?:
          | T
          | {
              image?: T;
              eyebrow?: T;
              heading?: T;
              body?: T;
              ctaLabel?: T;
              id?: T;
              blockName?: T;
            };
        activities?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    fellowship?: T;
                    title?: T;
                    dateLabel?: T;
                    description?: T;
                    photos?:
                      | T
                      | {
                          photo?: T;
                          id?: T;
                        };
                    legacyPhotoPaths?:
                      | T
                      | {
                          path?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        churchHistory?:
          | T
          | {
              churchPortrait?: T;
              proclamationOfFaith?: T;
              historyHeading?: T;
              historyBody?: T;
              documents?:
                | T
                | {
                    label?: T;
                    year?: T;
                    description?: T;
                    file?: T;
                    legacyPdfPath?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        announcementsList?:
          | T
          | {
              heading?: T;
              subheading?: T;
              items?:
                | T
                | {
                    date?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        newsletter?:
          | T
          | {
              eyebrow?: T;
              heading?: T;
              subheading?: T;
              issues?:
                | T
                | {
                    title?: T;
                    date?: T;
                    description?: T;
                    file?: T;
                    legacyPdfPath?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        give?:
          | T
          | {
              heading?: T;
              subheading?: T;
              methods?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    detail?: T;
                    id?: T;
                  };
              taxNote?: T;
              scripture?: T;
              id?: T;
              blockName?: T;
            };
        visitorFaq?:
          | T
          | {
              modalTitle?: T;
              modalSubtitle?: T;
              introText?: T;
              faqs?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              closingNote?: T;
              closeButtonLabel?: T;
              id?: T;
              blockName?: T;
            };
        footer?:
          | T
          | {
              worshipTimesLine?: T;
              instagramUrl?: T;
              whoWeAreLinks?:
                | T
                | {
                    label?: T;
                    page?: T;
                    id?: T;
                  };
              getConnectedLinks?:
                | T
                | {
                    label?: T;
                    page?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  churchName: string;
  tagline?: string | null;
  /**
   * Heading for the welcome blurb, e.g. "Welcome to Our Family"
   */
  welcomeBlurbSubject?: string | null;
  /**
   * Main welcome paragraph shown in the About section.
   */
  welcomeBlurbText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Founding / history paragraph shown below the welcome blurb.
   */
  welcomeHistoryText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  address?: string | null;
  phone?: string | null;
  email?: string | null;
  /**
   * Primary pastor contact details shown in the contact section.
   */
  pastor?: {
    name?: string | null;
    email?: string | null;
    /**
     * Pastor cell phone number
     */
    cell?: string | null;
  };
  /**
   * YouTube channel or live stream URL
   */
  youtubeLiveUrl?: string | null;
  /**
   * Google Calendar embed ID (found in Calendar settings > Embed)
   */
  googleCalendarId?: string | null;
  /**
   * Full Google Maps iframe src URL for the contact section embed
   */
  googleMapsEmbedUrl?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-home".
 */
export interface PageHome {
  id: number;
  hero: {
    backgroundImage?: (number | null) | Media;
    eyebrow?: string | null;
    heading: string;
    subheading?: string | null;
  };
  sundayService: {
    image?: (number | null) | Media;
    eyebrow?: string | null;
    heading: string;
    body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    scheduleItems?:
      | {
          time: string;
          label: string;
          sub?: string | null;
          id?: string | null;
        }[]
      | null;
    watchLiveUrl?: string | null;
    watchLiveLabel?: string | null;
    findUsLabel?: string | null;
    addressLine?: string | null;
  };
  prayerFeature: {
    image?: (number | null) | Media;
    eyebrow?: string | null;
    heading: string;
    body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    ctaLabel?: string | null;
  };
  sermons: {
    heading: string;
    /**
     * Pin a specific sermon here. If left blank, the most recently uploaded sermon is shown automatically.
     */
    featuredSermon?: (number | null) | Sermon;
  };
  activities: {
    heading: string;
    items?:
      | {
          fellowship?: string | null;
          title: string;
          dateLabel?: string | null;
          description?: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          } | null;
          photos?:
            | {
                photo: number | Media;
                id?: string | null;
              }[]
            | null;
          /**
           * Only used while migrating images to the media library.
           */
          legacyPhotoPaths?:
            | {
                path?: string | null;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-about".
 */
export interface PageAbout {
  id: number;
  hero: {
    backgroundImage?: (number | null) | Media;
    eyebrow?: string | null;
    heading: string;
  };
  churchHistory?: {
    churchPortrait?: (number | null) | Media;
    proclamationOfFaith?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    historyHeading?: string | null;
    historyBody?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    documents?:
      | {
          label: string;
          year?: string | null;
          description?: string | null;
          file?: (number | null) | Media;
          legacyPdfPath?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-announcements".
 */
export interface PageAnnouncement {
  id: number;
  heading?: string | null;
  subheading?: string | null;
  items?:
    | {
        date: string;
        title: string;
        body?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-give".
 */
export interface PageGive {
  id: number;
  heading?: string | null;
  subheading?: string | null;
  methods?:
    | {
        icon?: string | null;
        title: string;
        description?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        detail?: string | null;
        id?: string | null;
      }[]
    | null;
  taxNote?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  scripture?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-gainesville-dew".
 */
export interface PageGainesvilleDew {
  id: number;
  eyebrow?: string | null;
  heading?: string | null;
  subheading?: string | null;
  issues?:
    | {
        title: string;
        date: string;
        description?: string | null;
        file?: (number | null) | Media;
        legacyPdfPath?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-fellowships".
 */
export interface PageFellowship {
  id: number;
  hero: {
    backgroundImage?: (number | null) | Media;
    heading: string;
    subtitle?: string | null;
    learnMoreLabel?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-leadership".
 */
export interface PageLeadership {
  id: number;
  hero: {
    backgroundImage?: (number | null) | Media;
    eyebrow?: string | null;
    heading: string;
  };
  introParagraph?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-contact".
 */
export interface PageContact {
  id: number;
  hero: {
    backgroundImage?: (number | null) | Media;
    heading: string;
    subheading?: string | null;
  };
  /**
   * Override default EN/ZH labels on the visitor connect form.
   */
  form?: {
    sectionHeading?: string | null;
    submitLabel?: string | null;
    successMessage?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  churchName?: T;
  tagline?: T;
  welcomeBlurbSubject?: T;
  welcomeBlurbText?: T;
  welcomeHistoryText?: T;
  address?: T;
  phone?: T;
  email?: T;
  pastor?:
    | T
    | {
        name?: T;
        email?: T;
        cell?: T;
      };
  youtubeLiveUrl?: T;
  googleCalendarId?: T;
  googleMapsEmbedUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-home_select".
 */
export interface PageHomeSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        backgroundImage?: T;
        eyebrow?: T;
        heading?: T;
        subheading?: T;
      };
  sundayService?:
    | T
    | {
        image?: T;
        eyebrow?: T;
        heading?: T;
        body?: T;
        scheduleItems?:
          | T
          | {
              time?: T;
              label?: T;
              sub?: T;
              id?: T;
            };
        watchLiveUrl?: T;
        watchLiveLabel?: T;
        findUsLabel?: T;
        addressLine?: T;
      };
  prayerFeature?:
    | T
    | {
        image?: T;
        eyebrow?: T;
        heading?: T;
        body?: T;
        ctaLabel?: T;
      };
  sermons?:
    | T
    | {
        heading?: T;
        featuredSermon?: T;
      };
  activities?:
    | T
    | {
        heading?: T;
        items?:
          | T
          | {
              fellowship?: T;
              title?: T;
              dateLabel?: T;
              description?: T;
              photos?:
                | T
                | {
                    photo?: T;
                    id?: T;
                  };
              legacyPhotoPaths?:
                | T
                | {
                    path?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-about_select".
 */
export interface PageAboutSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        backgroundImage?: T;
        eyebrow?: T;
        heading?: T;
      };
  churchHistory?:
    | T
    | {
        churchPortrait?: T;
        proclamationOfFaith?: T;
        historyHeading?: T;
        historyBody?: T;
        documents?:
          | T
          | {
              label?: T;
              year?: T;
              description?: T;
              file?: T;
              legacyPdfPath?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-announcements_select".
 */
export interface PageAnnouncementsSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  items?:
    | T
    | {
        date?: T;
        title?: T;
        body?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-give_select".
 */
export interface PageGiveSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  methods?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        detail?: T;
        id?: T;
      };
  taxNote?: T;
  scripture?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-gainesville-dew_select".
 */
export interface PageGainesvilleDewSelect<T extends boolean = true> {
  eyebrow?: T;
  heading?: T;
  subheading?: T;
  issues?:
    | T
    | {
        title?: T;
        date?: T;
        description?: T;
        file?: T;
        legacyPdfPath?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-fellowships_select".
 */
export interface PageFellowshipsSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        backgroundImage?: T;
        heading?: T;
        subtitle?: T;
        learnMoreLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-leadership_select".
 */
export interface PageLeadershipSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        backgroundImage?: T;
        eyebrow?: T;
        heading?: T;
      };
  introParagraph?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-contact_select".
 */
export interface PageContactSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        backgroundImage?: T;
        heading?: T;
        subheading?: T;
      };
  form?:
    | T
    | {
        sectionHeading?: T;
        submitLabel?: T;
        successMessage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}